### ISSUE TITLE
Unable to use in electron-md

### ISSUE THREAD

**Issue by UnixNight** [MiniDisc-wiki/atrac-api#12]
I get the following error when using this in electron-md. If I use the one hosted online by the wiki, it works fine.
```
TypeError: Failed to fetch
    at create.encodeATRAC3 (sandbox://static/js/main.2ecbff07.chunk.js:1:89871)
    at async create.export (sandbox://static/js/main.2ecbff07.chunk.js:1:85915)
    at async sandbox://static/js/main.2ecbff07.chunk.js:1:104899
```

**Comment by ddmunhoz** [comment]
too little too late, you have to host this behind an https server, otherwise it won't work. If I find time I'll rewrite this repo into something new. This has been abandoned for a while I guess.
